// Código DIVIPOLA de departamento (DANE) para cada nombre de departamento (mismas llaves que
// departmentCapitals). Cruzado desde public/geo/colombia.json (campo DPTO) vía geoNameToDept
// de data/mock.ts — permite filtrar municipioCoordinates por el departamento seleccionado.
export const departmentDivipola: Record<string, string> = {
  'Antioquia': '05',
  'Atlántico': '08',
  'Bogotá D.C.': '11',
  'Bolívar': '13',
  'Boyacá': '15',
  'Caldas': '17',
  'Caquetá': '18',
  'Cauca': '19',
  'Cesar': '20',
  'Córdoba': '23',
  'Cundinamarca': '25',
  'Chocó': '27',
  'Huila': '41',
  'La Guajira': '44',
  'Magdalena': '47',
  'Meta': '50',
  'Nariño': '52',
  'Norte de Santander': '54',
  'Quindío': '63',
  'Risaralda': '66',
  'Santander': '68',
  'Sucre': '70',
  'Tolima': '73',
  'Valle del Cauca': '76',
  'Arauca': '81',
  'Casanare': '85',
  'Putumayo': '86',
  'Amazonas': '91',
  'Guainía': '94',
  'Guaviare': '95',
  'Vaupés': '97',
  'Vichada': '99',
  'San Andrés': '88',
}
