// Nombre de departamento (igual que en data/mock.ts) -> nombre de su ciudad capital,
// usado para geocodificar (Open-Meteo geocodifica por nombre de ciudad, no de departamento).
export const departmentCapitals: Record<string, string> = {
  'Antioquia': 'Medellín',
  'Atlántico': 'Barranquilla',
  'Bogotá D.C.': 'Bogotá',
  'Bolívar': 'Cartagena',
  'Boyacá': 'Tunja',
  'Caldas': 'Manizales',
  'Caquetá': 'Florencia',
  'Cauca': 'Popayán',
  'Cesar': 'Valledupar',
  'Córdoba': 'Montería',
  'Cundinamarca': 'Bogotá',
  'Chocó': 'Quibdó',
  'Huila': 'Neiva',
  'La Guajira': 'Riohacha',
  'Magdalena': 'Santa Marta',
  'Meta': 'Villavicencio',
  'Nariño': 'Pasto',
  'Norte de Santander': 'Cúcuta',
  'Quindío': 'Armenia',
  'Risaralda': 'Pereira',
  'Santander': 'Bucaramanga',
  'Sucre': 'Sincelejo',
  'Tolima': 'Ibagué',
  'Valle del Cauca': 'Cali',
  'Arauca': 'Arauca',
  'Casanare': 'Yopal',
  'Putumayo': 'Mocoa',
  'Amazonas': 'Leticia',
  'Guainía': 'Inírida',
  'Guaviare': 'San José del Guaviare',
  'Vaupés': 'Mitú',
  'Vichada': 'Puerto Carreño',
}

export const departmentNames = Object.keys(departmentCapitals)
